name: Dagger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: depot-ubuntu-latest,dagger=0.18.9
    steps:
    - uses: actions/checkout@v4
    - name: Enable netlink
      run: sudo modprobe nbd
    - name: Test
      run: dagger --progress=plain call test --dir=.

  test-e2e:
    runs-on: depot-ubuntu-latest,dagger=0.18.9
    steps:
    - uses: actions/checkout@v4
    - name: Enable netlink
      run: sudo modprobe nbd
    - name: Test
      run: dagger --progress=plain call test --dir=. --tests="./e2e" --tags="e2e"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: make bin/runtime
