name: Dagger

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  # Used by golangci-lint to emit annotations that are picked up by github
  contents: read
  # Used by golangci-lint for only-new-issues
  pull-requests: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.2
        only-new-issues: true

    - name: Check go.mod tidiness
      run: |
        # Run go mod tidy and check if there are any changes
        go mod tidy -diff
        if [ $? -ne 0 ]; then
          echo ""
          echo "Error: go.mod or go.sum is not tidy."
          echo "Please run 'go mod tidy' to fix module dependencies."
          exit 1
        fi
        echo "go.mod and go.sum are tidy."

  test:
    needs: lint
    runs-on: depot-ubuntu-latest,dagger=0.18.9
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: dagger --progress=plain call test --dir=.

  test-e2e:
    needs: lint
    runs-on: depot-ubuntu-latest,dagger=0.18.9
    steps:
    - uses: actions/checkout@v4
    - name: Test
      run: dagger --progress=plain call test --dir=. --tests="./e2e" --tags="e2e"

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: make bin/runtime
